import { RFQ } from './types';

export const mockRFQData: RFQ[] = [
  {
    id: 'RFQ-2024-0156',
    title: 'Industrial Motors & Drives',
    vendor: 'PowerTech Industries',
    category: 'Electrical',
    value: 185000,
    items: 24,
    status: 'processing',
    assignedTo: 'Engineering',
    createdDate: '2024-01-15',
    dueDate: '2024-01-25',
    processingProgress: 65,
    priority: 'high',
    difficulty: 'high',
    fit: 'excellent',
    contractLength: 'long',
    leadTime: 45,
    material: 'Steel',
    size: 'Large',
    building: 'Building A',
  },
  {
    id: 'RFQ-2024-0155',
    title: 'Precision Bearings Set',
    vendor: 'BearingWorld Ltd.',
    category: 'Mechanical',
    value: 45200,
    items: 150,
    status: 'quoted',
    assignedTo: 'Finance',
    createdDate: '2024-01-14',
    dueDate: '2024-01-22',
    responseDate: '2024-01-18',
    quoteAmount: 43850,
    priority: 'medium',
    difficulty: 'medium',
    fit: 'good',
    contractLength: 'medium',
    leadTime: 21,
    material: 'Aluminum',
    size: 'Medium',
    building: 'Building B',
  },
  {
    id: 'RFQ-2024-0154',
    title: 'Steel Sheet Materials',
    vendor: 'MetalCorp Inc.',
    category: 'Raw Materials',
    value: 128500,
    items: 35,
    status: 'processing',
    assignedTo: 'Vendor',
    createdDate: '2024-01-13',
    dueDate: '2024-01-23',
    processingProgress: 40,
    priority: 'urgent',
    difficulty: 'very high',
    fit: 'fair',
    contractLength: 'multi-year',
    leadTime: 60,
    material: 'Steel',
    size: 'Extra Large',
    building: 'Main Plant',
  },
  {
    id: 'RFQ-2024-0153',
    title: 'Safety Equipment Package',
    vendor: 'SafetyFirst Corp.',
    category: 'Safety',
    value: 22800,
    items: 200,
    status: 'accepted',
    assignedTo: 'Procurement',
    createdDate: '2024-01-12',
    dueDate: '2024-01-20',
    responseDate: '2024-01-16',
    quoteAmount: 21500,
    priority: 'low',
    difficulty: 'low',
    fit: 'excellent',
    contractLength: 'short',
    leadTime: 14,
    material: 'Plastic',
    size: 'Small',
    building: 'Building C',
  },
  {
    id: 'RFQ-2024-0152',
    title: 'CNC Machine Components',
    vendor: 'TechParts Global',
    category: 'Components',
    value: 312000,
    items: 45,
    status: 'sent',
    assignedTo: 'Vendor',
    createdDate: '2024-01-11',
    dueDate: '2024-01-28',
    priority: 'high',
    difficulty: 'very high',
    fit: 'good',
    contractLength: 'multi-year',
    leadTime: 90,
    material: 'Composite',
    size: 'Large',
    building: 'Annex',
  },
  {
    id: 'RFQ-2024-0151',
    title: 'Hydraulic Systems',
    vendor: 'HydroFlow Systems',
    category: 'Mechanical',
    value: 78900,
    items: 18,
    status: 'processing',
    assignedTo: 'Engineering',
    createdDate: '2024-01-10',
    dueDate: '2024-01-24',
    processingProgress: 85,
    priority: 'medium',
    difficulty: 'high',
    fit: 'good',
    contractLength: 'medium',
    leadTime: 35,
    material: 'Steel',
    size: 'Medium',
    building: 'Building A',
  },
  {
    id: 'RFQ-2024-0150',
    title: 'Electronic Sensors Batch',
    vendor: 'SensorTech Inc.',
    category: 'Electronics',
    value: 56300,
    items: 500,
    status: 'quoted',
    assignedTo: 'Finance',
    createdDate: '2024-01-09',
    dueDate: '2024-01-19',
    responseDate: '2024-01-17',
    quoteAmount: 58200,
    priority: 'medium',
    difficulty: 'medium',
    fit: 'excellent',
    contractLength: 'long',
    leadTime: 28,
    material: 'Copper',
    size: 'Small',
    building: 'Building B',
  },
  {
    id: 'RFQ-2024-0149',
    title: 'Packaging Materials',
    vendor: 'PackPro Solutions',
    category: 'Consumables',
    value: 8500,
    items: 1000,
    status: 'rejected',
    assignedTo: 'Operations',
    createdDate: '2024-01-08',
    dueDate: '2024-01-16',
    responseDate: '2024-01-14',
    quoteAmount: 12800,
    priority: 'low',
    difficulty: 'low',
    fit: 'poor',
    contractLength: 'short',
    leadTime: 7,
    material: 'Plastic',
    size: 'Small',
    building: 'Warehouse',
  },
  {
    id: 'RFQ-2024-0148',
    title: 'Industrial Lubricants',
    vendor: 'LubeMax Corp.',
    category: 'Consumables',
    value: 15200,
    items: 80,
    status: 'expired',
    assignedTo: 'Operations',
    createdDate: '2024-01-05',
    dueDate: '2024-01-12',
    priority: 'low',
    difficulty: 'low',
    fit: 'fair',
    contractLength: 'short',
    leadTime: 10,
    material: 'Other',
    size: 'Medium',
    building: 'Main Plant',
  },
  {
    id: 'RFQ-2024-0147',
    title: 'Automation Controllers',
    vendor: 'AutoControl Systems',
    category: 'Electronics',
    value: 245000,
    items: 12,
    status: 'draft',
    assignedTo: 'Engineering',
    createdDate: '2024-01-18',
    dueDate: '2024-02-01',
    priority: 'high',
    difficulty: 'very high',
    fit: 'excellent',
    contractLength: 'multi-year',
    leadTime: 75,
    material: 'Composite',
    size: 'Medium',
    building: 'Building C',
  },
];
